operations_file_name = "operations"
operations_folder_name = "operation_definitions"


mcas_header = ("# coding=utf-8 \n" 
"from pi3diamond import pi3d \n"
"import numpy as np \n"
"import os \n" 
"import UserScripts.helpers.sequence_creation_helpers as sch; reload(sch) \n"
"import multi_channel_awg_seq as MCAS; reload(MCAS) \n"
"from "+ operations_folder_name + "." + operations_file_name + " import *\n"
"from collections import OrderedDict \n \n"
"seq_name = os.path.basename(__file__).split('.')[0] \n"
"nuclear = sch.create_nuclear(__file__) \n"
"with open(os.path.abspath(__file__).split('.')[0] + '.py', 'r') as f: \n"
"\tmeas_code = f.read() \n \n"
"def ret_ret_mcas(pdc):\n"
"\tdef ret_mcas(current_iterator_df):\n"
"\t\tmcas = MCAS.MultiChSeq(seq_name=seq_name, ch_dict={'2g': [1, 2], '128m': [1, 2]})\n"
"\t\tfor idx, _I_ in current_iterator_df.iterrows():\n\n")



mcas_footer= ("\n\t\t\tpi3d.gated_counter.set_n_values(mcas)\n"
"\t\treturn mcas\n"
"\treturn ret_mcas\n \n"
"def settings(pdc={}):\n"
"\tana_seq=[\n"
"\t['result', '<', 0, 0, 10, 2],\n"
"\t]\n\n"
"\tsch.settings(\n"
"\t\tnuclear=nuclear,\n"
"\t\tret_mcas=ret_ret_mcas(pdc),\n"
"\t\tanalyze_sequence=ana_seq,\n"
"\t\tpdc=pdc,\n"
"\t\tmeas_code=meas_code)\n\n"
"\tnuclear.x_axis_title = 'tau_half [mus]'\n"
"\tnuclear.analyze_type = 'consecutive'\n\n"
"\tpi3d.gated_counter.trace.analyze_type = 'consecutive'\n"
"\tpi3d.gated_counter.trace.consecutive_valid_result_numbers = [0]\n"
"\tpi3d.gated_counter.trace.average_results = True\n\n"
"\tnuclear.parameters = OrderedDict(\n"
"\t\t(\n"
"\t\t\t('sweeps', range(30)),\n"
"\t\t)\n"
"\t)\n"
"\tnuclear.number_of_simultaneous_measurements = 1\n\n" 
"def run_fun(abort, **kwargs):\n"
"\tpi3d.readout_duration = 150e6\n"
"\tnuclear.debug_mode = False\n"
"\tsettings()\n"
"\tnuclear.run(abort)")
